server:
  port: 8788

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://containers-us-west-16.railway.app:6328/railway?&serverTimezone=UTC
    username: postgres
    password: mge4qjpxF1VYcvqxBaqr

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 477199117227873
            client-secret: 78e18b373864ac09ae35c0bff958bc58
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
